baseURL = "https://koios.review/"
languageCode = "zh-cn"
MetaDataFormat: "yaml"
title = "Koiosの壁橱"
theme = "hugo-theme-yilia"


[[menu.subnav]]
    Name = "Github"
    URL= "https://github.com/coeusite"